
import '@/styles/globals.css'
import AllContexts from '@/context/AllContext'
import { theme } from '@/theme/theme'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <theme>
        {children}
        </theme>
      </body>
    </html>
  )
}
